# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/filipe/Imaging/programs/spsim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/filipe/Imaging/programs/spsim

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake

# Special rule for the target install/local
install/local/fast: install/local

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filipe/Imaging/programs/spsim/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filipe/Imaging/programs/spsim/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named spsim

# Build rule for target.
spsim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spsim

# fast build rule for target.
spsim/fast:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/build

# target to build an object file
amplification.o:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/amplification.o

# target to preprocess a source file
amplification.i:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/amplification.i

# target to generate assembly for a file
amplification.s:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/amplification.s

# target to build an object file
config.o:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/config.o

# target to preprocess a source file
config.i:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/config.i

# target to generate assembly for a file
config.s:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/config.s

# target to build an object file
diffraction.o:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/diffraction.o

# target to preprocess a source file
diffraction.i:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/diffraction.i

# target to generate assembly for a file
diffraction.s:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/diffraction.s

# target to build an object file
io.o:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/io.o

# target to preprocess a source file
io.i:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/io.i

# target to generate assembly for a file
io.s:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/io.s

# target to build an object file
molecule.o:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/molecule.o

# target to preprocess a source file
molecule.i:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/molecule.i

# target to generate assembly for a file
molecule.s:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/molecule.s

# target to build an object file
mpi.o:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/mpi.o

# target to preprocess a source file
mpi.i:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/mpi.i

# target to generate assembly for a file
mpi.s:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/mpi.s

# target to build an object file
noise.o:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/noise.o

# target to preprocess a source file
noise.i:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/noise.i

# target to generate assembly for a file
noise.s:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/noise.s

# target to build an object file
real_space.o:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/real_space.o

# target to preprocess a source file
real_space.i:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/real_space.i

# target to generate assembly for a file
real_space.s:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/real_space.s

# target to build an object file
spsim.o:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/spsim.o

# target to preprocess a source file
spsim.i:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/spsim.i

# target to generate assembly for a file
spsim.s:
	$(MAKE) -f CMakeFiles/spsim.dir/build.make CMakeFiles/spsim.dir/spsim.s

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... spsim"
	@echo "... amplification.o"
	@echo "... amplification.i"
	@echo "... amplification.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... diffraction.o"
	@echo "... diffraction.i"
	@echo "... diffraction.s"
	@echo "... io.o"
	@echo "... io.i"
	@echo "... io.s"
	@echo "... molecule.o"
	@echo "... molecule.i"
	@echo "... molecule.s"
	@echo "... mpi.o"
	@echo "... mpi.i"
	@echo "... mpi.s"
	@echo "... noise.o"
	@echo "... noise.i"
	@echo "... noise.s"
	@echo "... real_space.o"
	@echo "... real_space.i"
	@echo "... real_space.s"
	@echo "... spsim.o"
	@echo "... spsim.i"
	@echo "... spsim.s"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

